### ISSUE TITLE
Deprecated transitive dep on `cross-spawn-async`

### ISSUE THREAD

**Issue by mayank99** [sindresorhus/default-browser#13]
`cross-spawn-async` is deprecated and replaced by `cross-spawn`. This dependency comes indirectly from `xdg-default-browser` which hasn't been updated in a few years.

```
default-browser 3.1.0
└─┬ xdg-default-browser 2.1.0
  └─┬ execa 0.2.2
    └── cross-spawn-async 2.2.5
```

Not a big deal, just something I noticed.

**Comment by navin-moorthy** [comment]
Yes, I noticed it too.

<img width="801" alt="Screenshot 2023-03-22 at 11 47 59 AM" src="https://user-images.githubusercontent.com/39694575/226818382-170e4a6d-39a7-407f-9497-cfb10efb6d74.png">

**Comment by nbouvrette** [comment]
Just got this error today for some reason. I opened this [issue](https://github.com/kevva/xdg-default-browser/issues/3) but I am a bit skeptical it will ever get fixed given the lack of activity there.

@sindresorhus given it's barely a [single file repo](https://github.com/kevva/xdg-default-browser/blob/master/index.js) - would it be possible to port it directly into [default-browser](https://github.com/sindresorhus/default-browser)?
