### ISSUE TITLE
Support for windows

### ISSUE THREAD

**Issue by connor4312** [sindresorhus/default-browser#5]
It seems like we could get the default browser on Windows by running a command like

```
reg QUERY HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice /v ProgId
```

Which prints output like

```
HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice
    ProgId    REG_SZ    ChromeHTML
```

Or

```
HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice
    ProgId    REG_SZ    MSEdgeDHTML
```

We wouldn't be able to get a similarly compatible `id`, as far as I can see, but we could categorize and retrieve the `name`. E.g: https://github.com/microsoft/vscode-js-debug/blob/master/src/common/defaultBrowserProvider.ts

Would you be open to a PR to add support for this?

**Comment by sindresorhus** [comment]
Sure, PR welcome :)
