### ISSUE TITLE
reduce bundle size by 90%

### ISSUE THREAD

**Issue by milahu** [sindresorhus/default-browser#8]
the current solution for darwin is horrible
cos we need a [50 KB bundle](https://bundlephobia.com/result?p=default-browser@2.0.1)
to solve a problem that can be solved in like 1 KB

when on darwin, we can use platform-dependent [`child_process.spawnSync`](https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options) calls

```bash
#!/bin/bash
# https://stackoverflow.com/a/32465364/10440128

x=~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist; \
plutil -convert xml1 $x; \
grep 'https' -b3 $x | awk 'NR==2 {split($2, arr, "[><]"); print arr[3]}'; \
plutil -convert binary1 $x
```

this is just one sample solution

at first sight, the file in $x 
should not be converted back-and-forth between xml and binary format
only once from binary to xml
or something readable like JSON - yes, plutil can translate to json
also avoid using temp-files

here is a draft version, i have no darwin machine to test = no warranty

```js
// darwin os: get default browser name
// use the `plutil` tool https://www.manpagez.com/man/1/plutil/
const child_process = require('child_process');
const lsf = '~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist';
const lso = JSON.parse(child_process.spawnSync(
  'plutil', ['-convert', 'json', '-o', '-', lsf],
  {maxBuffer: Infinity, encoding: 'utf-8'}).stdout);
// find value in lso
// ....
// print lso
console.log(JSON.stringify(lso, null, 2));
```

but this is still a bad solution, the convert step should go

it should be even easier with

```js
// darwin os: get default browser name
// use the `defaults` tool https://ss64.com/osx/defaults.html
// defaults accepts short names for lsf
// https://superuser.com/a/20857/951886
const child_process = require('child_process');
const lsf = 'com.apple.LaunchServices';
const keyOfDefaultBrowser = 'TODO_key_path_here';
const val = child_process.spawnSync(
  'defaults', ['read', lsf, keyOfDefaultBrowser]).stdout;
```

the standard API function is [LSCopyDefaultApplicationURLForURL](https://developer.apple.com/documentation/coreservices/1448824-lscopydefaultapplicationurlforur)
(this is [used by electron](https://github.com/electron/electron/blob/31322400e72cdcf6fe929457d997f26b34535c6c/shell/browser/browser_mac.mm#L42-L43) to get default apps)
but its closed source, so we cant use that to get the key path

whos got a darwin machine?
what is the structure of `com.apple.LaunchServices`?

edit: [here](https://apple.stackexchange.com/questions/366386/is-it-possible-to-script-what-applications-should-open-certain-file-extensions/366402) is a sample output from `defaults read`
output format is [NeXTSTEP plist format](https://stackoverflow.com/questions/21511463/how-can-i-parse-the-output-of-defaults-read-on-os-x)

```
$ defaults read ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist
{
    LSHandlers =     (
                {
            LSHandlerContentType = "org.7-zip.7-zip-archive";
            LSHandlerPreferredVersions =             {
                LSHandlerRoleViewer = "-";
            };
            LSHandlerRoleViewer = "com.aone.keka";
        },
                {
            LSHandlerContentType = "public.html";
            LSHandlerPreferredVersions =             {
                LSHandlerRoleAll = "-";
            };
            LSHandlerRoleAll = "com.apple.safari";
        }
    );
}
```

ugly! and expensive to parse

so back to
`plutil -convert json -o - com.apple.LaunchServices`
then the minimal solution should be
(using the logic from [default-browser-id](https://github.com/sindresorhus/default-browser-id/blob/e1e342b18fd078ecd0818de52f8d932a4db28461/index.js#L16))

```js
// darwin os: get default browser name
// use the `plutil` tool https://www.manpagez.com/man/1/plutil/
const child_process = require('child_process');
const getDefaultBrowserOnDarwin = () => (
	JSON.parse(child_process.execSync(
		"plutil -convert json -o - ~/Library/Preferences/com.apple.LaunchServices/com.apple.launchservices.secure.plist",
		{maxBuffer: 1/0, encoding: "utf-8"}
	)).LSHandlers.filter(h => h.LSHandlerURLScheme == "http")
	.map(h => h.LSHandlerRoleAll).filter(Boolean)[0]
	|| 'com.apple.Safari'
);
```
that is 414 bytes of code : P

told ya, we can do this in a 1 KB bundle

**Comment by milahu** [comment]
done. reduced bundle size by 99.76% : D

```js
// get-default-browser-name.js
// size is 1337 bytes
// license is CC0-1.0

// usage
// const g = require('./get-default-browser-name.js');
// const b = g();
// const r = g({raw:1});

const
c=require('child_process'),
s=require('os'),
x={maxBuffer:1/0, encoding:'utf-8'};

module.exports=(a)=>([[
[/(linux|freebsd)/,()=>(
	[c.execSync('xdg-mime query default text/html',x)]
	.map(r=>a.raw?r:r.match(/^.*?-(.*)-.*?/)[1])[0])],
[/darwin/,()=>(
	JSON.parse(c.execSync('plutil -convert json -o - '+
		'~/Library/Preferences/com.apple.LaunchServices/'+
		'com.apple.launchservices.secure.plist',x))
	.LSHandlers.filter(h => h.LSHandlerURLScheme == 'http')
	.map(h => h.LSHandlerRoleAll).filter(Boolean)[0]
	|| 'com.apple.Safari')],
[/win32/,()=>(
	[s.release().slice(0,3)=='10.'
	? ['HKEY_CURRENT_USER/SOFTWARE/Microsoft/Windows/Shell/'+
		'Associations/URLAssociations/http/UserChoice',
		'ProgId',/.* {4}(.*?)\r/,/^(.*)(\.HTTP|URL|HTML)/,'edge']
	: ['HKCU/Software/Clients/StartMenuInternet',
		'REG_SZ',/REG_SZ  "(.*?)"/,/.*\\(.*)\..*?$/,'ie']
	].map(([p,k,e,f,d])=>c.execSync(
		`reg query ${p.replace(/\//g,'\\')} `+
		// TODO remove findstr?
		`| findstr ${k}`,x).match(e)).map(r=>r?r[1]:'')
	.map(r=>a.raw?r:[r.match(f)].map(r=>r?r[1]:d)[0])[0])],
].find(x=>s.platform().match(x[0]))
[1]().trim()].map(r=>a.raw?r:r.toLowerCase())[0]
)
```

**Comment by sindresorhus** [comment]
Yeah, it could probably be improved. However, the priority was performance, not size. Spawning is very slow.
